dist: trusty

language: generic

sudo: required

before_install:
    - sudo pip install bashate
    - sudo apt-get install pcregrep

script:
    - sudo bash ./integration-tests/int-newline-errors.sh
    - sudo bash ./integration-tests/int-bashate.sh
    - sudo bash ./integration-tests/int-shellcheck.sh
    - sudo bash ./integration-tests/int-apps-install-uninstall.sh

matrix:
  fast_finish: true

notifications:
    webhooks: https://www.travisbuddy.com/
